name: 'AI Agent'
description: 'Execute GitHub Models API with MCP Tools'
author: 'mazrean'
branding:
  icon: 'battery-charging'
  color: 'blue'
inputs:
  prompt:
    description: The prompt for the model
    required: true
  model:
    description: The model to use
    required: false
    default: 'openai/gpt-4.1'
  base-url:
    description: The base url to use
    required: false
    default: 'https://models.github.ai'
  system-prompt:
    description: The system prompt for the model
    required: false
    default: 'You are a helpful assistant'
  max-tokens:
    description: The maximum number of tokens to generate
    required: false
    default: '4000'
  token:
    description: The token to use
    required: false
    default: ${{ github.token }}
  mcp-config-file:
    description: The MCP config file to use
    required: false
    default: './.ai-actions/mcp.json'
  memory-db-file:
    description: The memory db file to use
    required: false
    default: './.ai-actions/memory.db'
  timeout:
    description: The timeout for the model
    required: false

outputs:
  response:
    description: The response from the model
    value: ${{ steps.run.outputs.response }}

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install dependencies
      shell: bash
      run: pnpm install --prod
      working-directory: ${{ github.action_path }}
    - name: Run AI Agent
      id: run
      shell: bash
      env:
        PROMPT: ${{ inputs.prompt }}
        MODEL: ${{ inputs.model }}
        BASE_URL: ${{ inputs.base-url }}
        SYSTEM_PROMPT: ${{ inputs.system-prompt }}
        MAX_TOKENS: ${{ inputs.max-tokens }}
        TOKEN: ${{ inputs.token }}
        MCP_CONFIG_FILE: ${{ inputs.mcp-config-file }}
        MEMORY_DB_FILE: ${{ inputs.memory-db-file }}
        TIMEOUT: ${{ inputs.timeout }}
      run: node ${{ github.action_path }}/dist/index.mjs
