name: Main Branch CI

on:
  push:
    branches:
      - main

permissions:
  models: read

jobs:
  ai_agent_run:
    name: Run AI Agent action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: AI Agent action
        uses: ./
