name: Release

on:
  push:
    tags:
      - "v*"

env:
  TAG_NAME: ${{ github.event.ref }}
permissions:
  contents: write

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.ref }} tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
